#include "sqlite.h"

static const char SQL_CREATE[];

/*
static int callback(void *NotUsed, int argc, char *argv[], char *azColName[]) {
    int i;
    for (i = 0; i < argc; i++) {
        printf("%s = %s\n", azColName[i], argv[i] ? argv[i] : "NULL");
    }
    printf("\n");
    return 0;
}
*/

void do_sqlite_test(char *filename) {
    sqlite3 *db;
    int rc = sqlite3_open(filename, &db);

    if (rc) {
        fprintf(stderr, "Can't open database: %s\n", sqlite3_errmsg(db));
        return;
    } else {
        fprintf(stderr, "Opened database successfully\n");
    }

    char *errMsg = 0;
    rc = sqlite3_exec(db, SQL_CREATE, NULL, 0, &errMsg);
    if (rc != SQLITE_OK) {
        fprintf(stderr, "SQL error: %s\n", errMsg);
        sqlite3_free(errMsg);
    } else {
        fprintf(stdout, "Tables created successfully\n");
    }

    sqlite3_close(db);
}

static const char SQL_CREATE[] =
        "/*\n"
        "Navicat SQLite Data Transfer\n"
        "\n"
        "Source Server         : TM\n"
        "Source Server Version : 31300\n"
        "Source Host           : :0\n"
        "\n"
        "Target Server Type    : SQLite\n"
        "Target Server Version : 31300\n"
        "File Encoding         : 65001\n"
        "\n"
        "Date: 2018-06-18 19:21:43\n"
        "*/\n"
        "\n"
        "PRAGMA foreign_keys = OFF;\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for CalcUnitTypes\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"CalcUnitTypes\";\n"
        "CREATE TABLE \"CalcUnitTypes\" (\n"
        "\"Id\"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,\n"
        "\"CalcUnitType\"  TEXT NOT NULL\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for Cells\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"Cells\";\n"
        "CREATE TABLE \"Cells\" (\n"
        "\"ExpressionId\"  INTEGER NOT NULL,\n"
        "\"SheetId\"  INTEGER NOT NULL,\n"
        "\"Column\"  INTEGER NOT NULL,\n"
        "\"Row\"  INTEGER NOT NULL,\n"
        "\"Comment\"  TEXT,\n"
        "PRIMARY KEY (\"ExpressionId\"),\n"
        "CONSTRAINT \"fkey0\" FOREIGN KEY (\"SheetId\") REFERENCES \"Sheets\" (\"Id\"),\n"
        "CONSTRAINT \"fkey1\" FOREIGN KEY (\"ExpressionId\") REFERENCES \"Expressions\" (\"Id\"),\n"
        "UNIQUE (\"SheetId\" ASC, \"Column\", \"Row\")\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for Deps\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"Deps\";\n"
        "CREATE TABLE \"Deps\" (\n"
        "\"ReferenceId\"  INTEGER NOT NULL,\n"
        "\"DepReferenceId\"  INTEGER NOT NULL,\n"
        "PRIMARY KEY (\"ReferenceId\", \"DepReferenceId\"),\n"
        "CONSTRAINT \"fkey0\" FOREIGN KEY (\"ReferenceId\") REFERENCES \"Refs\" (\"Id\"),\n"
        "CONSTRAINT \"fkey1\" FOREIGN KEY (\"DepReferenceId\") REFERENCES \"Refs\" (\"Id\")\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for Expressions\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"Expressions\";\n"
        "CREATE TABLE \"Expressions\" (\n"
        "\"Id\"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,\n"
        "\"Expression\"  TEXT NOT NULL,\n"
        "\"ExpressionTypeId\"  INTEGER NOT NULL,\n"
        "\"CalcUnitTypeId\"  INTEGER NOT NULL,\n"
        "\"ValueTypeId\"  INTEGER NOT NULL,\n"
        "CONSTRAINT \"fkey0\" FOREIGN KEY (\"ExpressionTypeId\") REFERENCES \"ExpressionTypes\" (\"Id\"),\n"
        "CONSTRAINT \"fkey1\" FOREIGN KEY (\"CalcUnitTypeId\") REFERENCES \"CalcUnitTypes\" (\"Id\"),\n"
        "CONSTRAINT \"fkey2\" FOREIGN KEY (\"ValueTypeId\") REFERENCES \"ValueTypes\" (\"Id\")\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for ExpressionTypes\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"ExpressionTypes\";\n"
        "CREATE TABLE \"ExpressionTypes\" (\n"
        "\"Id\"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,\n"
        "\"ExpressionType\"  TEXT NOT NULL\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for FormulaValues\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"FormulaValues\";\n"
        "CREATE TABLE \"FormulaValues\" (\n"
        "\"ExpressionId\"  INTEGER NOT NULL,\n"
        "\"Value\"  TEXT,\n"
        "\"ScenarioId\"  INTEGER,\n"
        "PRIMARY KEY (\"ExpressionId\" ASC),\n"
        "CONSTRAINT \"fkey0\" FOREIGN KEY (\"ExpressionId\") REFERENCES \"Expressions\" (\"Id\"),\n"
        "CONSTRAINT \"fkey1\" FOREIGN KEY (\"ScenarioId\") REFERENCES \"Scenarios\" (\"Id\")\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for Names\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"Names\";\n"
        "CREATE TABLE \"Names\" (\n"
        "\"ExpressionId\"  INTEGER NOT NULL,\n"
        "\"Name\"  TEXT NOT NULL,\n"
        "\"SheetId\"  INTEGER,\n"
        "PRIMARY KEY (\"ExpressionId\" ASC),\n"
        "CONSTRAINT \"fkey0\" FOREIGN KEY (\"ExpressionId\") REFERENCES \"Expressions\" (\"Id\"),\n"
        "CONSTRAINT \"fkey1\" FOREIGN KEY (\"SheetId\") REFERENCES \"Sheets\" (\"Id\"),\n"
        "UNIQUE (\"SheetId\" ASC, \"Name\")\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for Refs\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"Refs\";\n"
        "CREATE TABLE \"Refs\" (\n"
        "\"Id\"  INTEGER NOT NULL,\n"
        "\"Reference\"  TEXT NOT NULL,\n"
        "\"ExpressionId\"  INTEGER,\n"
        "PRIMARY KEY (\"Id\" ASC),\n"
        "CONSTRAINT \"fkey0\" FOREIGN KEY (\"ExpressionId\") REFERENCES \"Expressions\" (\"Id\"),\n"
        "UNIQUE (\"Reference\" ASC),\n"
        "UNIQUE (\"ExpressionId\")\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for Scenarios\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"Scenarios\";\n"
        "CREATE TABLE \"Scenarios\" (\n"
        "\"Id\"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,\n"
        "\"Name\"  TEXT NOT NULL,\n"
        "UNIQUE (\"Name\")\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for Sheets\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"Sheets\";\n"
        "CREATE TABLE \"Sheets\" (\n"
        "\"Id\"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,\n"
        "\"Name\"  TEXT NOT NULL,\n"
        "UNIQUE (\"Name\")\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for ValueTypes\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"ValueTypes\";\n"
        "CREATE TABLE \"ValueTypes\" (\n"
        "\"Id\"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,\n"
        "\"TypeName\"  TEXT NOT NULL\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- Table structure for XmlParts\n"
        "-- ----------------------------\n"
        "DROP TABLE IF EXISTS \"main\".\"XmlParts\";\n"
        "CREATE TABLE \"XmlParts\" (\n"
        "\"Guid\"  TEXT NOT NULL,\n"
        "\"RootName\"  TEXT NOT NULL,\n"
        "\"Xml\"  TEXT NOT NULL,\n"
        "UNIQUE (\"Guid\")\n"
        ");\n"
        "\n"
        "-- ----------------------------\n"
        "-- View structure for ViewCells\n"
        "-- ----------------------------\n"
        "DROP VIEW IF EXISTS \"main\".\"ViewCells\";\n"
        "CREATE VIEW \"ViewCells\" AS \n"
        "SELECT\n"
        "Sheets.Name AS SheetName,\n"
        "Cells.SheetId,\n"
        "Cells.\"Column\",\n"
        "Cells.\"Row\",\n"
        "ExpressionTypes.ExpressionType,\n"
        "Expressions.ExpressionTypeId,\n"
        "Expressions.Expression,\n"
        "FormulaValues.Value,\n"
        "ValueTypes.TypeName AS ValueType,\n"
        "Expressions.ValueTypeId,\n"
        "Cells.Comment\n"
        "FROM\n"
        "Cells\n"
        "INNER JOIN Sheets ON Cells.SheetId = Sheets.Id\n"
        "INNER JOIN Expressions ON Cells.ExpressionId = Expressions.Id\n"
        "LEFT JOIN FormulaValues ON FormulaValues.ExpressionId = Expressions.Id\n"
        "INNER JOIN ExpressionTypes ON Expressions.ExpressionTypeId = ExpressionTypes.Id\n"
        "INNER JOIN ValueTypes ON Expressions.ValueTypeId = ValueTypes.Id\n"
        "WHERE\n"
        "Expressions.CalcUnitTypeId = 1;\n"
        "\n"
        "-- ----------------------------\n"
        "-- View structure for ViewExpressions\n"
        "-- ----------------------------\n"
        "DROP VIEW IF EXISTS \"main\".\"ViewExpressions\";\n"
        "CREATE VIEW \"ViewExpressions\" AS SELECT\n"
        "Expressions.Expression,\n"
        "ExpressionTypes.ExpressionType,\n"
        "Expressions.ExpressionTypeId,\n"
        "CalcUnitTypes.CalcUnitType,\n"
        "Expressions.CalcUnitTypeId,\n"
        "Cells.SheetId AS CellSheetId,\n"
        "Cells.\"Column\" AS CellColumn,\n"
        "Cells.\"Row\" AS CellRow,\n"
        "Names.SheetId AS NameSheetId,\n"
        "Names.Name\n"
        "FROM\n"
        "Expressions\n"
        "LEFT JOIN Cells ON Cells.ExpressionId = Expressions.Id\n"
        "LEFT JOIN Names ON Names.ExpressionId = Expressions.Id\n"
        "INNER JOIN ExpressionTypes ON Expressions.ExpressionTypeId = ExpressionTypes.Id\n"
        "INNER JOIN CalcUnitTypes ON Expressions.CalcUnitTypeId = CalcUnitTypes.Id;\n"
        "\n"
        "-- ----------------------------\n"
        "-- View structure for ViewNames\n"
        "-- ----------------------------\n"
        "DROP VIEW IF EXISTS \"main\".\"ViewNames\";\n"
        "CREATE VIEW \"ViewNames\" AS \n"
        "SELECT\n"
        "Names.SheetId,\n"
        "Names.Name,\n"
        "ExpressionTypes.ExpressionType,\n"
        "Expressions.ExpressionTypeId,\n"
        "Expressions.Expression,\n"
        "FormulaValues.Value,\n"
        "ValueTypes.TypeName AS ValueType,\n"
        "Expressions.ValueTypeId\n"
        "FROM\n"
        "Names\n"
        "INNER JOIN Expressions ON Names.ExpressionId = Expressions.Id\n"
        "INNER JOIN ExpressionTypes ON Expressions.ExpressionTypeId = ExpressionTypes.Id\n"
        "INNER JOIN ValueTypes ON Expressions.ValueTypeId = ValueTypes.Id\n"
        "LEFT JOIN FormulaValues ON FormulaValues.ExpressionId = Expressions.Id\n"
        "WHERE\n"
        "Expressions.CalcUnitTypeId = 2;\n"
        "PRAGMA foreign_keys = ON;";
